from todo.api.v1 import views
from rest_framework.routers import DefaultRouter

app_name = "api-v1"

# Initialize a DefaultRouter instance to automatically generate routes for the registered viewsets.
router = DefaultRouter()

# Register the TaskModelViewSet with the router.
# The 'task' prefix will be used in the URL patterns for the TaskModelViewSet.
# The 'task' basename will be used in the URL patterns for the TaskModelViewSet.
router.register("task", viewset=views.TaskModelViewSet, basename="task")

# The urlpatterns variable will hold the URL patterns generated by the router.
urlpatterns = router.urls
