name: Docker Image CI and Development

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    Test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Set up Docker
              run: |
                  sudo apt-get update
                  sudo apt-get install -y docker-compose

            - name: Setup Docker-Compose
              run: docker-compose up -d

            - name: Run Tests
              run: docker compose exec backend sh -c "flake8 && pytest ."

    Deploy:
        if: ${{ always() && contains(join(needs.Test.result, ','), 'success') }}
        name: Deploy
        runs-on: ubuntu-latest
        needs: Test
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Connect and Execute Commands
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.DOCKER_HOST }}
                  port: ${{ secrets.DOCKER_PORT }}
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
                  script: |
                      cd ${{ secrets.PROJECT_PATH }}
                      docker compose -f docker-compose-stage.yml stop
                      git pull
                      docker compose -f docker-compose-stage.yml restart
